---
title: "VSV 2023 Notes"
description: " California Outbreak."
date: "2025-04-18"
categories: [R, VSNJ]
output-dir: docs
format:
  gfm:
   toc: true
   toc-depth: 2
   code-fold: show
   code-summary: "Hide code"
   preview-mode: raw
editor: source
editor_options:  
  chunk_output_type: console
---

## Libraries
```{r warning=FALSE, message=FALSE}
library(here)
library(tidyverse)
library(ggmap)
library(ggspatial)
library(sf)
library(terra)

# Phylo
library(ape) #Analyses of Phylogenetics and Evolution (APE)
library(phangorn) # phylogenetic trees and networks
#library(rentrez) # R interface to the NCBI - GenBank
library(Biostrings) # sequence wrangling
library(msa) # Multiple Sequence Alignment (MSA) algorithms  
library(ggtree) # tree visualization and annotation
```


## Custom Functions
```{r}
# source(here("R/utilities.R"))
# source_dir(here("R"))
```


```{r}
alignment <- read.dna(here("local/world.fasta"),
                      format="fasta", as.matrix=TRUE)
```

```{r}
ggtree(alignment)
```




